server:
  port: 8092

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/food_orders_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      baseline-version: 1
      schemas: public
      validate-on-migrate: true
      clean-on-validation-error: false
      out-of-order: false
      table: flyway_schema_history
jwt:
  secret: hits2025972303hits2025972303hits20259723032025hits
  lifetime: 30m

