server:
  port: 8000

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AsmrS4/config-service.git
          clone-on-start: true
