package com.example.user_service.utils;

public class FeatureFlagConstants {
    public static String ENABLE_SAVE_EDITED_USER = "ENABLE_SAVE_EDITED_USER";
    public static String ENABLE_BAD_STATUS_INSTEAD_OF_SUCCESS = "ENABLE_BAD_STATUS_INSTEAD_OF_SUCCESS";
    public static String ENABLE_CHANGE_PASSWORD = "ENABLE_CHANGE_PASSWORD";
    public static String ENABLE_STAFF_AUTH_VIA_PHONE_NUMBER = "ENABLE_STAFF_AUTH_VIA_PHONE_NUMBER";
    public static String ENABLE_REFRESH_SESSION = "ENABLE_REFRESH_SESSION";
    public static String ENABLE_INTERNAL_SERVER_ERROR = "ENABLE_INTERNAL_SERVER_ERROR";
    public static String ENABLE_SAVE_NULLABLE_PROPS = "ENABLE_SAVE_NULLABLE_PROPS";
    public static String ENABLE_RETURN_EMPTY_RESULT = "ENABLE_RETURN_EMPTY_RESULT";
    public static String ENABLE_MIXED_UP_TOKENS = "ENABLE_MIXED_UP_TOKENS";
    public static String ENABLE_EXPIRED_ACCESS_TOKEN = "ENABLE_EXPIRED_ACCESS_TOKEN";
    public static String ENABLE_OPERATORS_WITH_CLIENTS_BUG = "ENABLE_OPERATORS_WITH_CLIENTS_BUG";
}
